version: '3.7'

services: 
        php:
                build: 
                        context: ./PHP
                        dockerfile: Dockerfile
                ports: 
                        - 666:80/tcp
                volumes: 
                        - "./DocumentRoot:/var/www/html"
                networks: 
                        - backend
                        - frontend
        
        baza:
                image: mysql:5.7
                volumes: 
                        - "./data:/var/lib/mysql"
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: bartki
                        MYSQL_USER: bartek
                        MYSQL_PASSWORD: bartek
                networks: 
                        - backend
        
        phpmyadmin:
                image: phpmyadmin/phpmyadmin
                ports: 
                        - 8080:80
                environment: 
                        PMA_HOST: baza
                        MYSQL_ROOT_PASSWORD: password
                depends_on: 
                        - baza
                networks: 
                        - backend
networks: 
        frontend: 
        backend: 
volumes: 
        data:

        
